# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI Experiment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/workflows/*.yml'
      - '!**/workflows/maven.yml'
  pull_request:
    paths-ignore:
      - '**/workflows/*.yml'
      - '!**/workflows/maven.yml'

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [ 8 ]
        include:
          # Update java 21/ubuntu to add deploy step
          - java: 8
            os: ubuntu-latest
            deploy: true
#          - java: 23-ea
#            os: ubuntu-latest
#            experimental: true        
#          - java: 23-ea
#            os: windows-latest
#            experimental: true        
#          - java: 23-ea
#            os: macos-latest
#            experimental: true        
      fail-fast: false
        
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        persist-credentials: false
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        # these values cause the plugin to set up the Maven settings.xml file
        server-id: apache.snapshots.https # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: NEXUS_USER # env variable for username in deploy
        server-password: NEXUS_PW # env variable for token in deploy
    
    
    - name: Initialize Energy Estimation
      uses: green-coding-berlin/eco-ci-energy-estimation@3f407abfca265dc2d37f2cf889b569a3589f8479 # use hash or @vX here (See note below)
      with:
        task: start-measurement

    - name: Build with Maven
      run: mvn -Dproject.build.sourceEncoding=UTF-8 --show-version --batch-mode --no-transfer-progress -DtrimStackTrace=false
    
    - name: Build measurement
      if: always()
      uses: green-coding-berlin/eco-ci-energy-estimation@3f407abfca265dc2d37f2cf889b569a3589f8479 # use hash or @vX here (See note below)
      with:
        task: get-measurement
        label: 'Build measurement'

    - name: Show Energy Results
      if: always()
      uses: green-coding-berlin/eco-ci-energy-estimation@3f407abfca265dc2d37f2cf889b569a3589f8479 # use hash or @vX here (See note below)
      id: total-measurement-step
      with:
        task: display-results

    - name: Upload total energy data artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: total-energy-data
        path: /tmp/eco-ci/total-data.json

    - name: Upload lap energy data artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lap-energy-data
        path: /tmp/eco-ci/lap-data.json

    - name: Upload pom.xml artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pom.xml
        path: pom.xml
      # - name: Deploy SNAPSHOT using minimal build
    #   if: matrix.deploy && github.repository == 'apache/commons-io' && github.ref_name == 'master' 
    #   env:
    #     NEXUS_USER: ${{ secrets.NEXUS_USER }}
    #     NEXUS_PW: ${{ secrets.NEXUS_PW }}
    #   run: >
    #     echo "Deploy SNAPSHOT" >> $GITHUB_STEP_SUMMARY;
    #     mvn --show-version --batch-mode --no-transfer-progress deploy -Dgpg.skip 
    #     -DskipTests -Drat.skip -Djacoco.skip -Dcyclonedx.skip -Dspotbugs.skip -Dspdx.skip -Dpmd.skip
